version: "3.9"


services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - app_socket:/tmp/app/
      - ./nginx/project.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"


volumes:
  mongo_data:
